/**
 * Copyright (c) 2016-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

// Code generated by "stringer -type=MessageType packet6.go"; DO NOT EDIT

package dhcplb

import "fmt"

const _MessageType_name = "SolicitAdvertiseRequestConfirmRenewRebindReplyReleaseDeclineReconfigureInformationRequestRelayForwRelayRepl"

var _MessageType_index = [...]uint8{0, 7, 16, 23, 30, 35, 41, 46, 53, 60, 71, 89, 98, 107}

func (i MessageType) String() string {
	i -= 1
	if i >= MessageType(len(_MessageType_index)-1) {
		return fmt.Sprintf("MessageType(%d)", i+1)
	}
	return _MessageType_name[_MessageType_index[i]:_MessageType_index[i+1]]
}
