/**
 * Copyright (c) 2016-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

// Code generated by "stringer -type=OptionType packet6.go"; DO NOT EDIT

package dhcplb

import "fmt"

const (
	_OptionType_name_0 = "ClientIdServerIdIdentAssocNonTempAddrIdentAssocTempAddrIaAddrOptionRequestPreferenceElapsedTimeRelayMessage"
	_OptionType_name_1 = "AuthServerUnicastStatusCodeRapidCommitUserClassVendorClassVendorOptsInterfaceIdReconfigureMessageReconfigureAccept"
)

var (
	_OptionType_index_0 = [...]uint8{0, 8, 16, 37, 55, 61, 74, 84, 95, 107}
	_OptionType_index_1 = [...]uint8{0, 4, 17, 27, 38, 47, 58, 68, 79, 97, 114}
)

func (i OptionType) String() string {
	switch {
	case 1 <= i && i <= 9:
		i -= 1
		return _OptionType_name_0[_OptionType_index_0[i]:_OptionType_index_0[i+1]]
	case 11 <= i && i <= 20:
		i -= 11
		return _OptionType_name_1[_OptionType_index_1[i]:_OptionType_index_1[i+1]]
	default:
		return fmt.Sprintf("OptionType(%d)", i)
	}
}
