name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # TODO: fix lint
          args: -D errcheck
