name: Lint

on:
  push:

jobs:
  lint:
    name: Lint Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.15.4'
      - name: Convert to modules
        run: go mod init github.com/facebookincubator/dhcplb
        
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          skip-go-installation: true
          args: --timeout 300s
